import React, {useEffect, useRef, useState} from 'react';
import {Box, Text, useInput} from 'ink';
import {BookProject} from '../services/project.js';
import {ExportFormat, exportBook} from '../services/export.js';

export function ExportScreen({
  project,
  onBack,
  onDependencies,
  initialFormat,
}: {
  project: BookProject;
  onBack: () => void;
  onDependencies: () => void;
  initialFormat?: ExportFormat;
}) {
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('Choose an export format.');
  const autoStarted = useRef(false);

  async function runExport(format: ExportFormat) {
    setBusy(true);
    try {
      await exportBook(project, format, setMessage);
    } catch (error) {
      setMessage(error instanceof Error ? error.message : String(error));
    } finally {
      setBusy(false);
    }
  }

  useEffect(() => {
    if (!initialFormat || autoStarted.current) return;
    autoStarted.current = true;
    void runExport(initialFormat);
  }, [initialFormat]);

  useInput((input, key) => {
    if (busy) return;
    if (input.toLowerCase() === 'e') void runExport('epub');
    else if (input.toLowerCase() === 'p') void runExport('pdf');
    else if (input.toLowerCase() === 'd') onDependencies();
    else if (key.escape || input.toLowerCase() === 'q') onBack();
  });

  return (
    <Box flexDirection="column" paddingX={1}>
      <Box borderStyle="round" borderColor="cyan" paddingX={1}>
        <Text bold color="cyan">Export · {project.book.title}</Text>
      </Box>
      <Box flexDirection="column" borderStyle="round" marginTop={1} paddingX={1}>
        <Text bold>[E] EPUB 3</Text>
        <Text dimColor>Portable ebook with metadata, table of contents, citations, and cover image.</Text>
        <Text bold>[P] PDF</Text>
        <Text dimColor>Print-ready document generated by Pandoc and {project.book.output.pdfEngine}.</Text>
        <Text bold>[D] Dependencies</Text>
        <Text dimColor>Check or install the external tools used by the export pipeline.</Text>
      </Box>
      <Text>Esc back</Text>
      <Text color={message.startsWith('Created') ? 'green' : 'white'}>{busy ? '◌ ' : ''}{message}</Text>
    </Box>
  );
}
